apiVersion: v1
kind: Service
metadata:
  name: toxiproxy
  labels:
    app.kubernetes.io/name: toxiproxy
spec:
  selector:
    app.kubernetes.io/name: toxiproxy
  ports:
    - name: api
      port: 8474
      targetPort: api
{{- range .Values.proxies }}
    - name: {{ .name }}
      port: {{ (splitList ":" .listen) | last }}
      targetPort: {{ .name }}
{{- end }}
