{{- $gwType := include "gateway.systemType" . -}}
{{- if and .Values.dumpsCollector.install .Values.dumpsCollector.ingress.install (contains "legacy-ingress" $gwType) }}
{{- $tlsBackend := or (eq (include "isTlsGenerateCertsEnabled" .) "true") (eq (include "isTlsUseExistingCertsEnabled" .) "true") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Values.dumpsCollector.name }}'
  labels:
    {{- include "common.namedLabels" .Values.dumpsCollector | nindent 4 }}
    {{- include "common.commonLabels" . | nindent 4 }}
    deployment.netcracker.com/ingress-type: private-network
    deployment.netcracker.com/ingress-audience-type: ops-user
  {{- if or $tlsBackend (contains "gateway-api-default" $gwType) }}
  annotations:
    {{- if $tlsBackend }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end }}
    {{- if contains "gateway-api-default" $gwType }}
    gateway-api-converter.netcracker.com/ignore: "true"
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.dumpsCollector.ingress.className }}
  ingressClassName: {{ .Values.dumpsCollector.ingress.className }}
  {{- end }}
  rules:
    - host: {{ include "dumpsCollector.ingress" . }}
      http:
        paths:
          - path: /
            {{- if (.Capabilities.APIVersions.Has "networking.k8s.io/v1") }}
            pathType: Prefix
            backend:
              service:
                name: '{{ .Values.dumpsCollector.service.name }}'
                port:
                  name: http
            {{- end }}
{{- end }}
