// Package wire holds the low-level encoding primitives of the agent's stream
// formats, shared by the virtual dumper (production generator) and the
// synthetic test builders in libs/tests/helpers/wire. The generated bytes are
// disposable; these encoders are the versioned source of truth
// (backend/docs/design/WORKFLOW.md §6).
package wire

import (
	"bytes"
	"encoding/binary"
	"unicode/utf16"
)

// CallsHeaderMagic marks a versioned calls file. The agent writes
// (magic<<32 | version) as the first fixed long
// (CompressedLocalAndRemoteOutputStream.rotate).
const CallsHeaderMagic = 0xFFFEFDFC

// CallsFormatVersion is the calls-record format the agent writes and
// libs/parser/pipe/calls.go reads.
const CallsFormatVersion = 4

// MaxPhraseSize is the agent's MAX_PHRASE_SIZE (ProtocolConst.java): the
// capacity of one phrase buffer on the phrase-framed streams.
const MaxPhraseSize = 10240

func PutFixedLong(buf *bytes.Buffer, v uint64) {
	var b [8]byte
	binary.BigEndian.PutUint64(b[:], v)
	buf.Write(b[:])
}

func PutFixedInt(buf *bytes.Buffer, v uint32) {
	var b [4]byte
	binary.BigEndian.PutUint32(b[:], v)
	buf.Write(b[:])
}

func PutVarInt(buf *bytes.Buffer, v uint64) {
	for v >= 0x80 {
		buf.WriteByte(byte(v) | 0x80)
		v >>= 7
	}
	buf.WriteByte(byte(v))
}

func PutZigZag(buf *bytes.Buffer, v int64) {
	PutVarInt(buf, uint64((v<<1)^(v>>63)))
}

// PutVarString mirrors the agent's DataOutputStreamEx.write(String)
// (common/.../dump/DataOutputStreamEx.java): a varint length that is the UTF-16
// code-unit count — Java's s.length(), not the code-point count — followed by
// writeChars, two big-endian bytes per code unit.
//
// The distinction matters for non-BMP characters. An emoji is one Go rune but
// two UTF-16 code units (a surrogate pair), so the length is 2 and both halves
// go on the wire. Encoding by rune instead would write length 1 and truncate
// the rune to a single 16-bit unit — a string the real agent never emits, which
// is why the earlier rune-based encoder hid the readChar-signedness and
// surrogate-pair decoder bugs. For BMP-only strings the two encodings are
// byte-identical, so existing ASCII fixtures are unaffected.
func PutVarString(buf *bytes.Buffer, s string) {
	units := utf16.Encode([]rune(s))
	PutVarInt(buf, uint64(len(units)))
	for _, u := range units {
		var b [2]byte
		binary.BigEndian.PutUint16(b[:], u)
		buf.Write(b[:])
	}
}
