// Package wire builds synthetic profiler wire-format streams for tests.
//
// The generated bytes are disposable; this generator is the versioned source of
// truth (backend/docs/design/WORKFLOW.md §6). It encodes the calls stream the
// way the agent's Dumper writes it: a file header, then one record per closed
// call whose start time is a zig-zag varint delta from the previous record.
package wire

import (
	"bytes"
	"encoding/binary"
)

// callsHeaderMagic marks a versioned calls file. The agent writes
// (magic<<32 | version) as the first fixed long
// (CompressedLocalAndRemoteOutputStream.rotate).
const callsHeaderMagic = 0xFFFEFDFC

// CallsStream encodes a version-1 calls stream with one record per entry in
// deltasMs, all on a single thread ("main"). baseMs is the absolute Unix-ms
// epoch stored in the file header. Each record's wire time is a delta from the
// previous record, so a decoder must accumulate to recover the absolute start:
//
//	ts_ms[0] = baseMs + deltasMs[0]
//	ts_ms[i] = ts_ms[i-1] + deltasMs[i]
//
// See backend/docs/design/01-write-contract.md §5.1.
func CallsStream(baseMs int64, deltasMs []int64) []byte {
	buf := &bytes.Buffer{}
	putFixedLong(buf, uint64(callsHeaderMagic)<<32|1) // format marker + version 1
	putFixedLong(buf, uint64(baseMs))                 // base_ms

	for i, delta := range deltasMs {
		putZigZag(buf, delta) // start time: delta from the previous record
		putVarInt(buf, 7)     // method (dictionary tag id)
		putVarInt(buf, 42)    // duration
		putVarInt(buf, 1)     // child calls
		putVarInt(buf, 0)     // thread index 0
		if i == 0 {
			putVarString(buf, "main") // first use of a thread carries its name
		}
		putVarInt(buf, 0) // logs written
		putVarInt(buf, 0) // logs generated - logs written
		putVarInt(buf, 0) // trace file index
		putVarInt(buf, 0) // buffer offset
		putVarInt(buf, 0) // record index
		putVarInt(buf, 0) // param count
	}
	return buf.Bytes()
}

func putFixedLong(buf *bytes.Buffer, v uint64) {
	var b [8]byte
	binary.BigEndian.PutUint64(b[:], v)
	buf.Write(b[:])
}

func putVarInt(buf *bytes.Buffer, v uint64) {
	for v >= 0x80 {
		buf.WriteByte(byte(v) | 0x80)
		v >>= 7
	}
	buf.WriteByte(byte(v))
}

func putZigZag(buf *bytes.Buffer, v int64) {
	putVarInt(buf, uint64((v<<1)^(v>>63)))
}

func putVarString(buf *bytes.Buffer, s string) {
	runes := []rune(s)
	putVarInt(buf, uint64(len(runes)))
	for _, r := range runes {
		var b [2]byte
		binary.BigEndian.PutUint16(b[:], uint16(r))
		buf.Write(b[:])
	}
}
