// Package wire builds synthetic profiler wire-format streams for tests.
//
// The generated bytes are disposable; this generator is the versioned source of
// truth (backend/docs/design/WORKFLOW.md §6). It encodes the calls stream the
// way the agent's Dumper writes it: a file header, then one record per closed
// call whose start time is a zig-zag varint delta from the previous record.
package wire

import (
	"bytes"
	"encoding/binary"
	"sort"
	"unicode/utf16"
)

// callsHeaderMagic marks a versioned calls file. The agent writes
// (magic<<32 | version) as the first fixed long
// (CompressedLocalAndRemoteOutputStream.rotate).
const callsHeaderMagic = 0xFFFEFDFC

// CallRecord is one closed root call in a synthetic calls stream. Field order
// and encoding follow the version-4 wire format the Go decoder reads
// (backend/libs/parser/pipe/calls.go).
type CallRecord struct {
	DeltaMs        int64 // start time as a delta from the previous record (from base_ms for the first)
	Method         int   // dictionary tag id of the root method
	DurationMs     int
	ChildCalls     int
	ThreadName     string // registered in the per-file thread table on first use
	TraceFileIndex int    // agent stream-file index at the start of the call's trace bytes
	BufferOffset   int    // offset within TraceFileIndex where the call's first chunk begins
	RecordIndex    int    // event index of the root ENTER within that chunk
	Params         map[int][]string

	// format >= 1 counters; the wire carries LogsWritten and
	// (LogsGenerated − LogsWritten) as unsigned varints, so LogsGenerated
	// must be ≥ LogsWritten.
	LogsGenerated int64
	LogsWritten   int64

	// format >= 2
	CpuTimeMs  int64
	WaitTimeMs int64
	MemoryUsed int64

	// format >= 3
	FileRead    int64
	FileWritten int64
	NetRead     int64
	NetWritten  int64

	// format >= 4
	Transactions int
	QueueWaitMs  int
}

// CallsStream encodes a version-1 calls stream with one record per entry in
// deltasMs, all on a single thread ("main"). baseMs is the absolute Unix-ms
// epoch stored in the file header. Each record's wire time is a delta from the
// previous record, so a decoder must accumulate to recover the absolute start:
//
//	ts_ms[0] = baseMs + deltasMs[0]
//	ts_ms[i] = ts_ms[i-1] + deltasMs[i]
//
// See backend/docs/design/01-write-contract.md §5.1.
func CallsStream(baseMs int64, deltasMs []int64) []byte {
	records := make([]CallRecord, len(deltasMs))
	for i, delta := range deltasMs {
		records[i] = CallRecord{
			DeltaMs:    delta,
			Method:     7,
			DurationMs: 42,
			ChildCalls: 1,
			ThreadName: "main",
		}
	}
	return CallsStreamRecords(baseMs, records)
}

// CallsStreamRecords encodes a version-4 calls stream from explicit records.
// The thread-name table mirrors the agent's: a thread name is written inline on
// first use and referenced by index afterwards, so records are NOT decodable in
// isolation from the file.
func CallsStreamRecords(baseMs int64, records []CallRecord) []byte {
	buf := &bytes.Buffer{}
	putFixedLong(buf, uint64(callsHeaderMagic)<<32|4) // format marker + version 4
	putFixedLong(buf, uint64(baseMs))                 // base_ms

	threadIndex := map[string]int{}
	for _, r := range records {
		putZigZag(buf, r.DeltaMs) // start time: delta from the previous record
		putVarInt(buf, uint64(r.Method))
		putVarInt(buf, uint64(r.DurationMs))
		putVarInt(buf, uint64(r.ChildCalls))
		idx, known := threadIndex[r.ThreadName]
		if !known {
			idx = len(threadIndex)
			threadIndex[r.ThreadName] = idx
		}
		putVarInt(buf, uint64(idx))
		if !known {
			putVarString(buf, r.ThreadName) // first use of a thread carries its name
		}
		putVarInt(buf, uint64(r.LogsWritten))
		putVarInt(buf, uint64(r.LogsGenerated-r.LogsWritten)) // wire carries the difference
		putVarInt(buf, uint64(r.TraceFileIndex))
		putVarInt(buf, uint64(r.BufferOffset))
		putVarInt(buf, uint64(r.RecordIndex))
		putVarInt(buf, uint64(r.CpuTimeMs)) // format >= 2
		putVarInt(buf, uint64(r.WaitTimeMs))
		putVarInt(buf, uint64(r.MemoryUsed))
		putVarInt(buf, uint64(r.FileRead)) // format >= 3
		putVarInt(buf, uint64(r.FileWritten))
		putVarInt(buf, uint64(r.NetRead))
		putVarInt(buf, uint64(r.NetWritten))
		putVarInt(buf, uint64(r.Transactions)) // format >= 4
		putVarInt(buf, uint64(r.QueueWaitMs))
		putVarInt(buf, uint64(len(r.Params)))
		paramIds := make([]int, 0, len(r.Params))
		for id := range r.Params {
			paramIds = append(paramIds, id)
		}
		sort.Ints(paramIds) // deterministic bytes for a versioned generator
		for _, id := range paramIds {
			values := r.Params[id]
			putVarInt(buf, uint64(id))
			putVarInt(buf, uint64(len(values)))
			// The decoder fills the result slice from the highest index down,
			// so multi-value params are written in reverse.
			for i := len(values) - 1; i >= 0; i-- {
				putVarString(buf, values[i])
			}
		}
	}
	return buf.Bytes()
}

func putFixedLong(buf *bytes.Buffer, v uint64) {
	var b [8]byte
	binary.BigEndian.PutUint64(b[:], v)
	buf.Write(b[:])
}

func putFixedInt(buf *bytes.Buffer, v uint32) {
	var b [4]byte
	binary.BigEndian.PutUint32(b[:], v)
	buf.Write(b[:])
}

func putVarInt(buf *bytes.Buffer, v uint64) {
	for v >= 0x80 {
		buf.WriteByte(byte(v) | 0x80)
		v >>= 7
	}
	buf.WriteByte(byte(v))
}

func putZigZag(buf *bytes.Buffer, v int64) {
	putVarInt(buf, uint64((v<<1)^(v>>63)))
}

// putVarString mirrors the agent's DataOutputStreamEx.write(String)
// (common/.../dump/DataOutputStreamEx.java): a varint length that is the UTF-16
// code-unit count — Java's s.length(), not the code-point count — followed by
// writeChars, two big-endian bytes per code unit.
//
// The distinction matters for non-BMP characters. An emoji is one Go rune but
// two UTF-16 code units (a surrogate pair), so the length is 2 and both halves
// go on the wire. Encoding by rune instead would write length 1 and truncate
// the rune to a single 16-bit unit — a string the real agent never emits, which
// is why the earlier rune-based encoder hid the readChar-signedness and
// surrogate-pair decoder bugs. For BMP-only strings the two encodings are
// byte-identical, so existing ASCII fixtures are unaffected.
func putVarString(buf *bytes.Buffer, s string) {
	units := utf16.Encode([]rune(s))
	putVarInt(buf, uint64(len(units)))
	for _, u := range units {
		var b [2]byte
		binary.BigEndian.PutUint16(b[:], u)
		buf.Write(b[:])
	}
}
