// Package wire builds synthetic profiler wire-format streams for tests.
//
// The generated bytes are disposable; this generator is the versioned source of
// truth (backend/docs/design/WORKFLOW.md §6). It encodes the calls stream the
// way the agent's Dumper writes it: a file header, then one record per closed
// call whose start time is a zig-zag varint delta from the previous record.
package wire

import (
	"bytes"

	emwire "github.com/Netcracker/qubership-profiler-backend/libs/emulator/wire"
)

// callsHeaderMagic marks a versioned calls file. The agent writes
// (magic<<32 | version) as the first fixed long
// (CompressedLocalAndRemoteOutputStream.rotate).
const callsHeaderMagic = emwire.CallsHeaderMagic

// CallRecord is one closed root call in a synthetic calls stream. Field order
// and encoding follow the version-4 wire format the Go decoder reads
// (backend/libs/parser/pipe/calls.go).
type CallRecord struct {
	DeltaMs        int64 // start time as a delta from the previous record (from base_ms for the first)
	Method         int   // dictionary tag id of the root method
	DurationMs     int
	ChildCalls     int
	ThreadName     string // registered in the per-file thread table on first use
	TraceFileIndex int    // agent stream-file index at the start of the call's trace bytes
	BufferOffset   int    // offset within TraceFileIndex where the call's first chunk begins
	RecordIndex    int    // event index of the root ENTER within that chunk
	Params         map[int][]string

	// format >= 1 counters; the wire carries LogsWritten and
	// (LogsGenerated − LogsWritten) as unsigned varints, so LogsGenerated
	// must be ≥ LogsWritten.
	LogsGenerated int64
	LogsWritten   int64

	// format >= 2
	CpuTimeMs  int64
	WaitTimeMs int64
	MemoryUsed int64

	// format >= 3
	FileRead    int64
	FileWritten int64
	NetRead     int64
	NetWritten  int64

	// format >= 4
	Transactions int
	QueueWaitMs  int
}

// CallsStream encodes a version-1 calls stream with one record per entry in
// deltasMs, all on a single thread ("main"). baseMs is the absolute Unix-ms
// epoch stored in the file header. Each record's wire time is a delta from the
// previous record, so a decoder must accumulate to recover the absolute start:
//
//	ts_ms[0] = baseMs + deltasMs[0]
//	ts_ms[i] = ts_ms[i-1] + deltasMs[i]
//
// See backend/docs/design/01-write-contract.md §5.1.
func CallsStream(baseMs int64, deltasMs []int64) []byte {
	records := make([]CallRecord, len(deltasMs))
	for i, delta := range deltasMs {
		records[i] = CallRecord{
			DeltaMs:    delta,
			Method:     7,
			DurationMs: 42,
			ChildCalls: 1,
			ThreadName: "main",
		}
	}
	return CallsStreamRecords(baseMs, records)
}

// CallsStreamRecords encodes a version-4 calls stream from explicit records.
// The record encoding — the per-file thread-name table, the zig-zag time
// deltas — lives in libs/emulator/wire.CallsFileState; this builder maps its
// delta-based records onto that encoder's absolute start times.
func CallsStreamRecords(baseMs int64, records []CallRecord) []byte {
	buf := &bytes.Buffer{}
	putFixedLong(buf, uint64(callsHeaderMagic)<<32|4) // format marker + version 4
	putFixedLong(buf, uint64(baseMs))                 // base_ms

	st := emwire.NewCallsFileState(baseMs)
	abs := baseMs
	for _, r := range records {
		abs += r.DeltaMs
		st.PutRecord(buf, emwire.CallRecord{
			StartMs:        abs,
			Method:         r.Method,
			DurationMs:     r.DurationMs,
			ChildCalls:     r.ChildCalls,
			ThreadName:     r.ThreadName,
			TraceFileIndex: r.TraceFileIndex,
			BufferOffset:   r.BufferOffset,
			RecordIndex:    r.RecordIndex,
			Params:         r.Params,
			LogsGenerated:  r.LogsGenerated,
			LogsWritten:    r.LogsWritten,
			CpuTimeMs:      r.CpuTimeMs,
			WaitTimeMs:     r.WaitTimeMs,
			MemoryUsed:     r.MemoryUsed,
			FileRead:       r.FileRead,
			FileWritten:    r.FileWritten,
			NetRead:        r.NetRead,
			NetWritten:     r.NetWritten,
			Transactions:   r.Transactions,
			QueueWaitMs:    r.QueueWaitMs,
		})
	}
	return buf.Bytes()
}

// The low-level encoders live in libs/emulator/wire so the virtual dumper
// (production generator) and these test builders share one source of truth;
// the aliases below keep this package's call sites unchanged.

func putFixedLong(buf *bytes.Buffer, v uint64) { emwire.PutFixedLong(buf, v) }

func putFixedInt(buf *bytes.Buffer, v uint32) { emwire.PutFixedInt(buf, v) }

func putVarInt(buf *bytes.Buffer, v uint64) { emwire.PutVarInt(buf, v) }

func putZigZag(buf *bytes.Buffer, v int64) { emwire.PutZigZag(buf, v) }

// putVarString writes the agent's var-string encoding; see
// libs/emulator/wire.PutVarString for the UTF-16 code-unit semantics and why
// they matter for non-BMP characters.
func putVarString(buf *bytes.Buffer, s string) { emwire.PutVarString(buf, s) }
