apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "profiler-backend.fullname" . }}-config
  labels:
    {{- include "profiler-backend.labels" (dict "root" . "component" "config") | nindent 4 }}
data:
  s3-endpoint: {{ include "profiler-backend.s3Endpoint" . | quote }}
  s3-bucket: {{ .Values.s3.bucket | quote }}
